services:
  redis:
    image: redis:7.0
    container_name:  goose_redis
    volumes:
      - redis-data:/data
  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:3.9.13-management
    container_name:  goose_rmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  goose:
    build: .
    container_name: goose_console
    ports:
      - 3000:3000
    environment:
      GOOSE_REDIS_HOST: redis
      GOOSE_REDIS_PORT: 6379
      GOOSE_RABBITMQ_HOST: rabbitmq
      GOOSE_RABBITMQ_PORT: 5672
      GOOSE_RABBITMQ_USERNAME: guest
      GOOSE_RABBITMQ_PASSWORD: guest
      GOOSE_TEST_REDIS_HOST: redis
      GOOSE_TEST_RABBITMQ_HOST: rabbitmq
      GOOSE_TEST_RABBITMQ_USERNAME: guest
      GOOSE_TEST_RABBITMQ_PASSWORD: guest
    depends_on:
      - redis
      - rabbitmq
volumes:
  redis-data:
  rabbitmq-data:
